WITH wm_fiscal_cal AS (
  SELECT
    d AS work_date,
    CASE
      WHEN d >= DATE '2026-01-31' THEN 2027
      WHEN d >= DATE '2025-02-01' THEN 2026
      ELSE 2025
    END AS WM_FISCAL_YEAR,
    CASE
      WHEN d >= DATE '2026-01-31' THEN
        DIV(DATE_DIFF(d, DATE '2026-01-31', DAY), 7) + 1
      WHEN d >= DATE '2025-02-01' THEN
        DIV(DATE_DIFF(d, DATE '2025-02-01', DAY), 7) + 1
      ELSE NULL
    END AS WM_FISCAL_WEEK,
    CASE
      WHEN d >= DATE '2026-01-31' THEN
        DATE_ADD(DATE '2026-01-31', INTERVAL (DIV(DATE_DIFF(d, DATE '2026-01-31', DAY), 7) * 7) DAY)
      WHEN d >= DATE '2025-02-01' THEN
        DATE_ADD(DATE '2025-02-01', INTERVAL (DIV(DATE_DIFF(d, DATE '2025-02-01', DAY), 7) * 7) DAY)
      ELSE NULL
    END AS WM_FISCAL_WEEK_START
  FROM UNNEST(
    GENERATE_DATE_ARRAY(DATE '2025-12-01', CURRENT_DATE())
  ) AS d
),
recent_wm_weeks AS (
  SELECT DISTINCT WM_FISCAL_YEAR, WM_FISCAL_WEEK, WM_FISCAL_WEEK_START
  FROM wm_fiscal_cal
  ORDER BY WM_FISCAL_YEAR DESC, WM_FISCAL_WEEK DESC
  LIMIT 13
),
dept_goals AS (
  SELECT
    SC_CODE_ID,
    FC_ID,
    GOAL,
    GOAL_UOM,
    ACTIVE_DATE,
    INACTIVE_DATE
  FROM `wmt-drax-prod.DRAX_VM.INPUTS_DEPARTMENTGOAL`
  WHERE FC_ID = 'TPA'
)
SELECT
  p.NETWORK_NAME,
  p.DEFAULT_ID        AS default_id,
  p.FC_ID,
  p.DATE              AS date,
  wfc.WM_FISCAL_YEAR,
  wfc.WM_FISCAL_WEEK,
  wfc.WM_FISCAL_WEEK_START,
  p.SC_CODE_ID,
  p.HOME_CODE_ID,
  p.AREA,
  p.SUPER_DEPARTMENT,
  p.DEPARTMENT,
  p.HOURS,
  p.IDLE_HOURS,
  p.VOLUME,
  dg.GOAL,
  dg.GOAL_UOM,
  SAFE_DIVIDE(p.VOLUME, p.HOURS)                             AS RATE_PER_HOUR,
  SAFE_DIVIDE(SAFE_DIVIDE(p.VOLUME, p.HOURS), dg.GOAL) * 100 AS PCT_TO_GOAL
FROM `wmt-drax-prod.DRAX_VM.VIEWS_ASSOCIATE_PERFORMANCE_DAY` p
INNER JOIN wm_fiscal_cal wfc
  ON p.DATE = wfc.work_date
INNER JOIN recent_wm_weeks rww
  ON wfc.WM_FISCAL_YEAR = rww.WM_FISCAL_YEAR
  AND wfc.WM_FISCAL_WEEK = rww.WM_FISCAL_WEEK
LEFT JOIN dept_goals dg
  ON p.SC_CODE_ID = dg.SC_CODE_ID
  AND p.DATE >= dg.ACTIVE_DATE
  AND (dg.INACTIVE_DATE IS NULL OR p.DATE < dg.INACTIVE_DATE)
WHERE p.FC_ID = 'TPA'
  AND p.HOURS > 0
ORDER BY p.DATE DESC, p.DEFAULT_ID, p.SC_CODE_ID
